#!/usr/bin/env python3
"""Embed bootloader/keys/slate_pub.pem as src/mcuboot_pubkey.cpp (uncompressed 0x04||X||Y).

Requires cryptography (pip install cryptography). If the PEM is missing/invalid,
writes an all-zero placeholder and exits 0 with a warning.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PEM = ROOT / "bootloader" / "keys" / "slate_pub.pem"
OUT = ROOT / "src" / "mcuboot_pubkey.cpp"


def uncompressed_pubkey(pem_path: Path) -> bytes | None:
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.backends import default_backend
    except ImportError:
        print("cryptography not installed — leaving zero placeholder", file=sys.stderr)
        return None
    try:
        data = pem_path.read_bytes()
        pub = serialization.load_pem_public_key(data, backend=default_backend())
        nums = pub.public_numbers()
        x = nums.x.to_bytes(32, "big")
        y = nums.y.to_bytes(32, "big")
        return b"\x04" + x + y
    except Exception as exc:  # noqa: BLE001
        print(f"could not parse {pem_path}: {exc}", file=sys.stderr)
        return None


def write_cpp(key: bytes) -> None:
    assert len(key) == 65
    lines = [
        "// Auto-generated by scripts/gen_pubkey_c.py — do not edit by hand.",
        "// Private key must never be committed. See bootloader/keys/README.md.",
        "",
        "#include <cstdint>",
        "",
        "namespace slate {",
        "namespace mcuboot {",
        "",
        "alignas(4) const std::uint8_t kEcdsaP256PubKey[65] = {",
    ]
    for i in range(0, 65, 8):
        chunk = key[i : i + 8]
        hexes = ", ".join(f"0x{b:02x}u" for b in chunk)
        comma = "," if i + 8 < 65 else ""
        lines.append(f"    {hexes}{comma}")
    lines += [
        "};",
        "",
        "const std::uint8_t* public_key() { return kEcdsaP256PubKey; }",
        "std::uint32_t public_key_len() { return sizeof(kEcdsaP256PubKey); }",
        "",
        "}  // namespace mcuboot",
        "}  // namespace slate",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


def main() -> int:
    key = uncompressed_pubkey(PEM) if PEM.is_file() else None
    if key is None:
        key = b"\x04" + bytes(64)
        print("WARNING: embedding zero pubkey — replace before production", file=sys.stderr)
    write_cpp(key)
    return 0


if __name__ == "__main__":
    sys.exit(main())
